### ISSUE TITLE
ComposerException: found undefined alias _door

### ISSUE THREAD

**Issue by mibby** [dmulloy2/LWC#10]
@dmulloy2 

LWC dev 10 errors at start-up every time. Downgrading to dev 9, it only errors when the wildcards are in the config.

```
[01:36:48] [Server thread/INFO]: [LWC] Enabling LWC v4.6.0-SNAPSHOT
[01:36:48] [Server thread/ERROR]: Error occurred while enabling LWC v4.6.0-SNAPSHOT (Is it up to date?)
org.yaml.snakeyaml.composer.ComposerException: found undefined alias _door
 in 'reader', line 56, column 9:
            *_door:
            ^

	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:136) ~[patched_1.11.2.jar:git-Paper-1055]
	at org.yaml.snakeyaml.composer.Composer.composeKeyNode(Composer.java:242) ~[patched_1.11.2.jar:git-Paper-1055]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:233) ~[patched_1.11.2.jar:git-Paper-1055]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:225) ~[patched_1.11.2.jar:git-Paper-1055]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[patched_1.11.2.jar:git-Paper-1055]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:246) ~[patched_1.11.2.jar:git-Paper-1055]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:237) ~[patched_1.11.2.jar:git-Paper-1055]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:225) ~[patched_1.11.2.jar:git-Paper-1055]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[patched_1.11.2.jar:git-Paper-1055]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:246) ~[patched_1.11.2.jar:git-Paper-1055]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:237) ~[patched_1.11.2.jar:git-Paper-1055]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:225) ~[patched_1.11.2.jar:git-Paper-1055]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[patched_1.11.2.jar:git-Paper-1055]
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[patched_1.11.2.jar:git-Paper-1055]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[patched_1.11.2.jar:git-Paper-1055]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120) ~[patched_1.11.2.jar:git-Paper-1055]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450) ~[patched_1.11.2.jar:git-Paper-1055]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:393) ~[patched_1.11.2.jar:git-Paper-1055]
	at com.griefcraft.util.config.Configuration.load(Configuration.java:188) ~[?:?]
	at com.griefcraft.util.config.Configuration.load(Configuration.java:207) ~[?:?]
	at com.griefcraft.util.config.Configuration.load(Configuration.java:137) ~[?:?]
	at com.griefcraft.util.config.Configuration.load(Configuration.java:105) ~[?:?]
	at com.griefcraft.lwc.LWC.<init>(LWC.java:211) ~[?:?]
	at com.griefcraft.lwc.LWCPlugin.onEnable(LWCPlugin.java:194) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[patched_1.11.2.jar:git-Paper-1055]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.11.2.jar:git-Paper-1055]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.11.2.jar:git-Paper-1055]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:378) [patched_1.11.2.jar:git-Paper-1055]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:328) [patched_1.11.2.jar:git-Paper-1055]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:209) [patched_1.11.2.jar:git-Paper-1055]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:603) [patched_1.11.2.jar:git-Paper-1055]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[01:36:48] [Server thread/INFO]: [LWC] Disabling LWC v4.6.0-SNAPSHOT
```

**Comment by akiraic** [comment]
Exactly same issue.

**Comment by PugaBear** [comment]
Huh, that is odd. Mine works fine with wildcards

**Comment by akiraic** [comment]
Clean install for me, dev 9 and 10 give the same error. last 1.11 spigot version.

**Comment by PugaBear** [comment]
Nevermind, I don't actually use the wildcards, thought I did. Maybe try escaping them? `\*_door:` idk

**Comment by akiraic** [comment]
OOOH how stupid am I? I just need to specify door by door instead of wildcards. Done.

**Comment by PugaBear** [comment]
Well yes that is one way. The idea of the wildcards was to make it simpler. :p

**Comment by dmulloy2** [comment]
Would appear to be an odd YAML quirk. Adding quotation marks around them should fix the issue.

**Comment by dmulloy2** [comment]
Fixed in https://github.com/dmulloy2/LWC/commit/aa04357dbe9b36271143289cfd9ce11eb7bd0467
