### ISSUE TITLE
SQLException: Streaming result set 

### ISSUE THREAD

**Issue by mibby** [dmulloy2/LWC#20]
LWC dev 15

```
[09:36:09] [Server thread/INFO]: player issued server command: /lwc admin purge eternal23
[09:36:09] [Thread-8/INFO]: [LWC] Keepalive packet (ping) failed!
[09:36:09] [Thread-8/WARN]: java.sql.SQLException: Streaming result set com.mysql.jdbc.RowDataDynamic@72aff75f is still active. No statements may be issued when any streaming result sets are open and in use on a given connection. Ensure that you have called .close() on any active streaming result sets before attempting more queries.
[09:36:09] [Thread-8/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:868)
[09:36:09] [Thread-8/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:864)
[09:36:09] [Thread-8/WARN]: 	at com.mysql.jdbc.MysqlIO.checkForOutstandingStreamingData(MysqlIO.java:3211)
[09:36:09] [Thread-8/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2443)
[09:36:09] [Thread-8/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2677)
[09:36:09] [Thread-8/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545)
[09:36:09] [Thread-8/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2503)
[09:36:09] [Thread-8/WARN]: 	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1369)
[09:36:09] [Thread-8/WARN]: 	at com.griefcraft.sql.Database.pingDatabase(Database.java:148)
[09:36:09] [Thread-8/WARN]: 	at com.griefcraft.util.DatabaseThread.flushDatabase(DatabaseThread.java:159)
[09:36:09] [Thread-8/WARN]: 	at com.griefcraft.util.DatabaseThread.run(DatabaseThread.java:177)
[09:36:09] [Thread-8/WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mibby** [comment]
Still an active issue.

```
[13:39:42] [Server thread/INFO]: player issued server command: /lwc admin purge prohunterpirate
[13:39:42] [Thread-5/WARN]: java.sql.SQLException: Streaming result set com.mysql.jdbc.RowDataDynamic@4752060d is still active. No statements may be issued when any streaming result sets are open and in use on a given connection. Ensure that you have called .close() on any active streaming result sets before attempting more queries.
[13:39:42] [Thread-5/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:868)
[13:39:42] [Thread-5/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:864)
[13:39:42] [Thread-5/WARN]: 	at com.mysql.jdbc.MysqlIO.checkForOutstandingStreamingData(MysqlIO.java:3214)
[13:39:42] [Thread-5/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2450)
[13:39:42] [Thread-5/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
[13:39:42] [Thread-5/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2486)
[13:39:42] [Thread-5/WARN]: 	at com.mysql.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:4778)
[13:39:42] [Thread-5/WARN]: 	at com.griefcraft.sql.Database.setAutoCommit(Database.java:175)
[13:39:42] [Thread-5/WARN]: 	at com.griefcraft.util.DatabaseThread.flushDatabase(DatabaseThread.java:138)
[13:39:42] [Thread-5/WARN]: 	at com.griefcraft.util.DatabaseThread.run(DatabaseThread.java:177)
[13:39:42] [Thread-5/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```
