### ISSUE TITLE
SQLException: No operations allowed after statement closed

### ISSUE THREAD

**Issue by mibby** [dmulloy2/LWC#24]
Paper dev 1170 (Spigot 1.12.1)
LWC dev 18

```
[20:25:13] [Server thread/INFO]: player issued server command: /lwc admin purge IchBinDerFuhrer
[20:25:13] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'lwc' in plugin LWC v4.6.0-SNAPSHOT
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.12.1.jar:git-Paper-1170]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.12.1.jar:git-Paper-1170]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:666) ~[patched_1.12.1.jar:git-Paper-1170]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1425) ~[patched_1.12.1.jar:git-Paper-1170]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1230) ~[patched_1.12.1.jar:git-Paper-1170]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.1.jar:git-Paper-1170]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.1.jar:git-Paper-1170]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.1.jar:git-Paper-1170]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.1.jar:git-Paper-1170]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.1.jar:git-Paper-1170]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424) [patched_1.12.1.jar:git-Paper-1170]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.1.jar:git-Paper-1170]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.1.jar:git-Paper-1170]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: com.griefcraft.scripting.ModuleException: LWC Module threw an uncaught exception! LWC version: 4.6.0
	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:358) ~[?:?]
	at com.griefcraft.lwc.LWCPlugin.onCommand(LWCPlugin.java:167) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.1.jar:git-Paper-1170]
	... 15 more
Caused by: com.griefcraft.scripting.ModuleException: java.sql.SQLException: No operations allowed after statement closed.
	at com.griefcraft.sql.Database.printException(Database.java:187) ~[?:?]
	at com.griefcraft.sql.PhysDB.invalidateHistory(PhysDB.java:1263) ~[?:?]
	at com.griefcraft.lwc.LWC.fastRemoveProtectionsByPlayer(LWC.java:940) ~[?:?]
	at com.griefcraft.modules.admin.AdminPurge.onCommand(AdminPurge.java:85) ~[?:?]
	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:340) ~[?:?]
	at com.griefcraft.lwc.LWCPlugin.onCommand(LWCPlugin.java:167) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.1.jar:git-Paper-1170]
	... 15 more
Caused by: java.sql.SQLException: No operations allowed after statement closed.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964) ~[patched_1.12.1.jar:git-Paper-1170]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:897) ~[patched_1.12.1.jar:git-Paper-1170]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:886) ~[patched_1.12.1.jar:git-Paper-1170]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860) ~[patched_1.12.1.jar:git-Paper-1170]
	at com.mysql.jdbc.StatementImpl.checkClosed(StatementImpl.java:442) ~[patched_1.12.1.jar:git-Paper-1170]
	at com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3340) ~[patched_1.12.1.jar:git-Paper-1170]
	at com.mysql.jdbc.PreparedStatement.setInt(PreparedStatement.java:3302) ~[patched_1.12.1.jar:git-Paper-1170]
	at com.griefcraft.sql.PhysDB.invalidateHistory(PhysDB.java:1258) ~[?:?]
	at com.griefcraft.lwc.LWC.fastRemoveProtectionsByPlayer(LWC.java:940) ~[?:?]
	at com.griefcraft.modules.admin.AdminPurge.onCommand(AdminPurge.java:85) ~[?:?]
	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:340) ~[?:?]
	at com.griefcraft.lwc.LWCPlugin.onCommand(LWCPlugin.java:167) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.1.jar:git-Paper-1170]
	... 15 more
```

**Comment by mibby** [comment]
:(

```
[17:58:28] [Server thread/INFO]: player issued server command: /lwc admin purge Dashingava505
[17:58:28] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'lwc' in plugin LWC v4.6.0-SNAPSHOT
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.12.1.jar:git-Paper-1190]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.12.1.jar:git-Paper-1190]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:672) ~[patched_1.12.1.jar:git-Paper-1190]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1425) ~[patched_1.12.1.jar:git-Paper-1190]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1230) ~[patched_1.12.1.jar:git-Paper-1190]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.1.jar:git-Paper-1190]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.1.jar:git-Paper-1190]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.1.jar:git-Paper-1190]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.1.jar:git-Paper-1190]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.1.jar:git-Paper-1190]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424) [patched_1.12.1.jar:git-Paper-1190]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.1.jar:git-Paper-1190]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.1.jar:git-Paper-1190]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: com.griefcraft.scripting.ModuleException: LWC Module threw an uncaught exception! LWC version: 4.6.0
	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:358) ~[?:?]
	at com.griefcraft.lwc.LWCPlugin.onCommand(LWCPlugin.java:167) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.1.jar:git-Paper-1190]
	... 15 more
Caused by: com.griefcraft.scripting.ModuleException: java.sql.SQLException: No operations allowed after statement closed.
	at com.griefcraft.sql.Database.printException(Database.java:187) ~[?:?]
	at com.griefcraft.sql.PhysDB.invalidateHistory(PhysDB.java:1263) ~[?:?]
	at com.griefcraft.lwc.LWC.fastRemoveProtectionsByPlayer(LWC.java:940) ~[?:?]
	at com.griefcraft.modules.admin.AdminPurge.onCommand(AdminPurge.java:85) ~[?:?]
	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:340) ~[?:?]
	at com.griefcraft.lwc.LWCPlugin.onCommand(LWCPlugin.java:167) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.1.jar:git-Paper-1190]
	... 15 more
Caused by: java.sql.SQLException: No operations allowed after statement closed.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964) ~[patched_1.12.1.jar:git-Paper-1190]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:897) ~[patched_1.12.1.jar:git-Paper-1190]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:886) ~[patched_1.12.1.jar:git-Paper-1190]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860) ~[patched_1.12.1.jar:git-Paper-1190]
	at com.mysql.jdbc.StatementImpl.checkClosed(StatementImpl.java:442) ~[patched_1.12.1.jar:git-Paper-1190]
	at com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3340) ~[patched_1.12.1.jar:git-Paper-1190]
	at com.mysql.jdbc.PreparedStatement.setInt(PreparedStatement.java:3302) ~[patched_1.12.1.jar:git-Paper-1190]
	at com.griefcraft.sql.PhysDB.invalidateHistory(PhysDB.java:1258) ~[?:?]
	at com.griefcraft.lwc.LWC.fastRemoveProtectionsByPlayer(LWC.java:940) ~[?:?]
	at com.griefcraft.modules.admin.AdminPurge.onCommand(AdminPurge.java:85) ~[?:?]
	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:340) ~[?:?]
	at com.griefcraft.lwc.LWCPlugin.onCommand(LWCPlugin.java:167) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.1.jar:git-Paper-1190]
	... 15 more

```

**Comment by mibby** [comment]
@dmulloy2 Commit https://github.com/dmulloy2/LWC/commit/edd2724626be1daf4a0bb69fd1b86738f55bee2e breaks LWC from loading.

This outputs at start-up every time trying to initialize.
```
[08:38:26] [Server thread/INFO]: [LWC] Enabling LWC v4.6.0-SNAPSHOT
[08:38:26] [Server thread/INFO]: [LWC] Connecting to MySQL
[08:38:26] [Server thread/INFO]: [LWC] Dropping old indexes (One time, may take a while!)
[08:38:26] [Server thread/INFO]: [LWC] Creating new indexes (One time, may take a while!)
[08:38:26] [Server thread/INFO]: [LWC] Creating index on internal
[08:38:26] [Server thread/WARN]: com.griefcraft.scripting.ModuleException: java.sql.SQLException: No operations allowed after statement closed.
[08:38:26] [Server thread/WARN]: 	at com.griefcraft.sql.Database.printException(Database.java:204)
[08:38:26] [Server thread/WARN]: 	at com.griefcraft.sql.PhysDB.fetch(PhysDB.java:128)
[08:38:26] [Server thread/WARN]: 	at com.griefcraft.sql.PhysDB.getProtectionCount(PhysDB.java:139)
[08:38:26] [Server thread/WARN]: 	at com.griefcraft.sql.PhysDB.load(PhysDB.java:400)
[08:38:26] [Server thread/WARN]: 	at com.griefcraft.lwc.LWC.load(LWC.java:1540)
[08:38:26] [Server thread/WARN]: 	at com.griefcraft.lwc.LWCPlugin.onEnable(LWCPlugin.java:203)
[08:38:26] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[08:38:26] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[08:38:26] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[08:38:26] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:382)
[08:38:26] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:331)
[08:38:26] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:224)
[08:38:26] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[08:38:26] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[08:38:26] [Server thread/WARN]: Caused by: java.sql.SQLException: No operations allowed after statement closed.
[08:38:26] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964)
[08:38:26] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:897)
[08:38:26] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:886)
[08:38:26] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860)
[08:38:26] [Server thread/WARN]: 	at com.mysql.jdbc.StatementImpl.checkClosed(StatementImpl.java:442)
[08:38:26] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1919)
[08:38:26] [Server thread/WARN]: 	at com.griefcraft.sql.PhysDB.fetch(PhysDB.java:118)
[08:38:26] [Server thread/WARN]: 	... 12 more
[08:38:26] [Server thread/ERROR]: Error occurred while enabling LWC v4.6.0-SNAPSHOT (Is it up to date?)
com.griefcraft.scripting.ModuleException: java.sql.SQLException: No operations allowed after statement closed.
	at com.griefcraft.sql.Database.printException(Database.java:204) ~[?:?]
	at com.griefcraft.sql.PhysDB.precache(PhysDB.java:873) ~[?:?]
	at com.griefcraft.lwc.LWC.load(LWC.java:1549) ~[?:?]
	at com.griefcraft.lwc.LWCPlugin.onEnable(LWCPlugin.java:203) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.1.jar:git-Paper-1199]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.1.jar:git-Paper-1199]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12.1.jar:git-Paper-1199]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:382) [patched_1.12.1.jar:git-Paper-1199]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:331) [patched_1.12.1.jar:git-Paper-1199]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:224) [patched_1.12.1.jar:git-Paper-1199]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.1.jar:git-Paper-1199]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.sql.SQLException: No operations allowed after statement closed.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964) ~[patched_1.12.1.jar:git-Paper-1199]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:897) ~[patched_1.12.1.jar:git-Paper-1199]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:886) ~[patched_1.12.1.jar:git-Paper-1199]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860) ~[patched_1.12.1.jar:git-Paper-1199]
	at com.mysql.jdbc.StatementImpl.checkClosed(StatementImpl.java:442) ~[patched_1.12.1.jar:git-Paper-1199]
	at com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3340) ~[patched_1.12.1.jar:git-Paper-1199]
	at com.mysql.jdbc.PreparedStatement.setInt(PreparedStatement.java:3302) ~[patched_1.12.1.jar:git-Paper-1199]
	at com.griefcraft.sql.PhysDB.precache(PhysDB.java:862) ~[?:?]
	... 10 more
[08:38:26] [Server thread/INFO]: [LWC] Disabling LWC v4.6.0-SNAPSHOT
[08:38:26] [Server thread/INFO]: [LWC] Flushing protection updates (0)
```

Downgrading from LWC dev 19 to dev 18 fixes the problem, but the initial SQLException still exists.

**Comment by mibby** [comment]
Bump. :(

```
[07:12:02] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'lwc' in plugin LWC v4.6.0-SNAPSHOT
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.12.2.jar:git-Paper-1244]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.12.2.jar:git-Paper-1244]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:676) ~[patched_1.12.2.jar:git-Paper-1244]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1466) ~[patched_1.12.2.jar:git-Paper-1244]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1271) ~[patched_1.12.2.jar:git-Paper-1244]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.2.jar:git-Paper-1244]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.2.jar:git-Paper-1244]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1244]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_152]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_152]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1244]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1244]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1244]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1244]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1244]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
Caused by: com.griefcraft.scripting.ModuleException: LWC Module threw an uncaught exception! LWC version: 4.6.0
	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:358) ~[LWC.jar:?]
	at com.griefcraft.lwc.LWCPlugin.onCommand(LWCPlugin.java:167) ~[LWC.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1244]
	... 15 more
Caused by: com.griefcraft.scripting.ModuleException: java.sql.SQLException: No operations allowed after statement closed.
	at com.griefcraft.sql.Database.printException(Database.java:187) ~[LWC.jar:?]
	at com.griefcraft.sql.PhysDB.invalidateHistory(PhysDB.java:1263) ~[LWC.jar:?]
	at com.griefcraft.lwc.LWC.fastRemoveProtectionsByPlayer(LWC.java:940) ~[LWC.jar:?]
	at com.griefcraft.modules.admin.AdminPurge.onCommand(AdminPurge.java:85) ~[LWC.jar:?]
	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:340) ~[LWC.jar:?]
	at com.griefcraft.lwc.LWCPlugin.onCommand(LWCPlugin.java:167) ~[LWC.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1244]
	... 15 more
Caused by: java.sql.SQLException: No operations allowed after statement closed.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964) ~[patched_1.12.2.jar:git-Paper-1244]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:897) ~[patched_1.12.2.jar:git-Paper-1244]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:886) ~[patched_1.12.2.jar:git-Paper-1244]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860) ~[patched_1.12.2.jar:git-Paper-1244]
	at com.mysql.jdbc.StatementImpl.checkClosed(StatementImpl.java:442) ~[patched_1.12.2.jar:git-Paper-1244]
	at com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3340) ~[patched_1.12.2.jar:git-Paper-1244]
	at com.mysql.jdbc.PreparedStatement.setInt(PreparedStatement.java:3302) ~[patched_1.12.2.jar:git-Paper-1244]
	at com.griefcraft.sql.PhysDB.invalidateHistory(PhysDB.java:1258) ~[LWC.jar:?]
	at com.griefcraft.lwc.LWC.fastRemoveProtectionsByPlayer(LWC.java:940) ~[LWC.jar:?]
	at com.griefcraft.modules.admin.AdminPurge.onCommand(AdminPurge.java:85) ~[LWC.jar:?]
	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:340) ~[LWC.jar:?]
	at com.griefcraft.lwc.LWCPlugin.onCommand(LWCPlugin.java:167) ~[LWC.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1244]
	... 15 more
```

**Comment by mibby** [comment]
@dmulloy2 Please fix. Can't even purge players from the database. :(

```
[15:20:10] [Server thread/INFO]: player issued server command: /lwc admin purge AwesomeRichWorld
[15:20:10] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'lwc' in plugin LWC v4.6.0-SNAPSHOT
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.12.2.jar:git-Paper-1250]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.12.2.jar:git-Paper-1250]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:676) ~[patched_1.12.2.jar:git-Paper-1250]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1471) ~[patched_1.12.2.jar:git-Paper-1250]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1276) ~[patched_1.12.2.jar:git-Paper-1250]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.2.jar:git-Paper-1250]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.2.jar:git-Paper-1250]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1250]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_152]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_152]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1250]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1250]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1250]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1250]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1250]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
Caused by: com.griefcraft.scripting.ModuleException: LWC Module threw an uncaught exception! LWC version: 4.6.0
	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:358) ~[LWC.jar:?]
	at com.griefcraft.lwc.LWCPlugin.onCommand(LWCPlugin.java:167) ~[LWC.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1250]
	... 15 more
Caused by: com.griefcraft.scripting.ModuleException: java.sql.SQLException: No operations allowed after statement closed.
	at com.griefcraft.sql.Database.printException(Database.java:187) ~[LWC.jar:?]
	at com.griefcraft.sql.PhysDB.invalidateHistory(PhysDB.java:1263) ~[LWC.jar:?]
	at com.griefcraft.lwc.LWC.fastRemoveProtectionsByPlayer(LWC.java:940) ~[LWC.jar:?]
	at com.griefcraft.modules.admin.AdminPurge.onCommand(AdminPurge.java:85) ~[LWC.jar:?]
	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:340) ~[LWC.jar:?]
	at com.griefcraft.lwc.LWCPlugin.onCommand(LWCPlugin.java:167) ~[LWC.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1250]
	... 15 more
Caused by: java.sql.SQLException: No operations allowed after statement closed.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964) ~[patched_1.12.2.jar:git-Paper-1250]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:897) ~[patched_1.12.2.jar:git-Paper-1250]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:886) ~[patched_1.12.2.jar:git-Paper-1250]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860) ~[patched_1.12.2.jar:git-Paper-1250]
	at com.mysql.jdbc.StatementImpl.checkClosed(StatementImpl.java:442) ~[patched_1.12.2.jar:git-Paper-1250]
	at com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3340) ~[patched_1.12.2.jar:git-Paper-1250]
	at com.mysql.jdbc.PreparedStatement.setInt(PreparedStatement.java:3302) ~[patched_1.12.2.jar:git-Paper-1250]
	at com.griefcraft.sql.PhysDB.invalidateHistory(PhysDB.java:1258) ~[LWC.jar:?]
	at com.griefcraft.lwc.LWC.fastRemoveProtectionsByPlayer(LWC.java:940) ~[LWC.jar:?]
	at com.griefcraft.modules.admin.AdminPurge.onCommand(AdminPurge.java:85) ~[LWC.jar:?]
	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:340) ~[LWC.jar:?]
	at com.griefcraft.lwc.LWCPlugin.onCommand(LWCPlugin.java:167) ~[LWC.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1250]
	... 15 more
```
