### ISSUE TITLE
cleanup broken

### ISSUE THREAD

**Issue by seema84** [dmulloy2/LWC#26]
Build #1​9
Command /lwc admin cleanup

error:
 null
org.bukkit.command.CommandException: Unhandled exception executing command 'lwc' in plugin LWC v4.6.0-SNAPSHOT
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit.jar:git-Spigot-65e8124-357b573]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[craftbukkit.jar:git-Spigot-65e8124-357b573]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:647) ~[craftbukkit.jar:git-Spigot-65e8124-357b573]
at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1386) [craftbukkit.jar:git-Spigot-65e8124-357b573]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1221) [craftbukkit.jar:git-Spigot-65e8124-357b573]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [craftbukkit.jar:git-Spigot-65e8124-357b573]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [craftbukkit.jar:git-Spigot-65e8124-357b573]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-65e8124-357b573]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [craftbukkit.jar:git-Spigot-65e8124-357b573]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [craftbukkit.jar:git-Spigot-65e8124-357b573]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [craftbukkit.jar:git-Spigot-65e8124-357b573]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [craftbukkit.jar:git-Spigot-65e8124-357b573]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [craftbukkit.jar:git-Spigot-65e8124-357b573]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: com.griefcraft.scripting.ModuleException: LWC Module threw an uncaught exception! LWC version: 4.6.0
at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:358) ~[?:?]
at com.griefcraft.lwc.LWCPlugin.onCommand(LWCPlugin.java:167) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.jar:git-Spigot-65e8124-357b573]
... 15 more
Caused by: com.griefcraft.scripting.ModuleException: java.sql.SQLException: No operations allowed after statement closed.
at com.griefcraft.sql.Database.printException(Database.java:204) ~[?:?]
at com.griefcraft.sql.PhysDB.fetch(PhysDB.java:128) ~[?:?]
at com.griefcraft.sql.PhysDB.getProtectionCount(PhysDB.java:139) ~[?:?]
at com.griefcraft.modules.admin.AdminCleanup.onCommand(AdminCleanup.java:88) ~[?:?]
at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:340) ~[?:?]
at com.griefcraft.lwc.LWCPlugin.onCommand(LWCPlugin.java:167) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.jar:git-Spigot-65e8124-357b573]
... 15 more
Caused by: java.sql.SQLException: No operations allowed after statement closed.
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964) ~[craftbukkit.jar:git-Spigot-65e8124-357b573]
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:897) ~[craftbukkit.jar:git-Spigot-65e8124-357b573]
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:886) ~[craftbukkit.jar:git-Spigot-65e8124-357b573]
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860) ~[craftbukkit.jar:git-Spigot-65e8124-357b573]
at com.mysql.jdbc.StatementImpl.checkClosed(StatementImpl.java:442) ~[craftbukkit.jar:git-Spigot-65e8124-357b573]
at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1919) ~[craftbukkit.jar:git-Spigot-65e8124-357b573]
at com.griefcraft.sql.PhysDB.fetch(PhysDB.java:118) ~[?:?]
at com.griefcraft.sql.PhysDB.getProtectionCount(PhysDB.java:139) ~[?:?]
at com.griefcraft.modules.admin.AdminCleanup.onCommand(AdminCleanup.java:88) ~[?:?]
at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:340) ~[?:?]
at com.griefcraft.lwc.LWCPlugin.onCommand(LWCPlugin.java:167) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.jar:git-Spigot-65e8124-357b573]
... 15 more

**Comment by seema84** [comment]
the build #1​9 is broken the full plugin not only this one command

**Comment by seema84** [comment]
ok thanks
