### ISSUE TITLE
NullPointerException resolveProtectionConfiguration

### ISSUE THREAD

**Issue by mibby** [dmulloy2/LWC#34]
http://ci.dmulloy2.net/job/LWC/23/

This message occurs when trying to punch a locked item frame you locked.
```[LWC] Internal error. Notify an admin immediately. :BLOCK_BREAK```

```
[02:42:14] [Server thread/WARN]: com.griefcraft.scripting.ModuleException: LWC Module threw an uncaught exception! LWC version: 4.6.0
[02:42:14] [Server thread/WARN]: 	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:358)
[02:42:14] [Server thread/WARN]: 	at com.griefcraft.listeners.LWCPlayerListener.onDamage(LWCPlayerListener.java:552)
[02:42:14] [Server thread/WARN]: 	at com.griefcraft.listeners.LWCPlayerListener.hangingBreakByEntityEvent(LWCPlayerListener.java:516)
[02:42:14] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor29.execute(Unknown Source)
[02:42:14] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)
[02:42:14] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[02:42:14] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[02:42:14] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515)
[02:42:14] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500)
[02:42:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityHanging.damageEntity(EntityHanging.java:184)
[02:42:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityItemFrame.damageEntity(EntityItemFrame.java:50)
[02:42:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityHanging.t(EntityHanging.java:164)
[02:42:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityHuman.attack(EntityHuman.java:953)
[02:42:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityPlayer.attack(EntityPlayer.java:1361)
[02:42:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1703)
[02:42:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49)
[02:42:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6)
[02:42:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[02:42:14] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[02:42:14] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[02:42:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[02:42:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843)
[02:42:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427)
[02:42:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[02:42:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[02:42:14] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[02:42:14] [Server thread/WARN]: Caused by: java.lang.NullPointerException
[02:42:14] [Server thread/WARN]: 	at com.griefcraft.lwc.LWC.resolveProtectionConfiguration(LWC.java:1496)
[02:42:14] [Server thread/WARN]: 	at com.griefcraft.modules.destroy.DestroyModule.onDestroyProtection(DestroyModule.java:58)
[02:42:14] [Server thread/WARN]: 	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:344)
[02:42:14] [Server thread/WARN]: 	... 25 more

```

**Comment by dmulloy2** [comment]
is this fixed?

**Comment by mibby** [comment]
Seems to be fixed, thanks.
