### ISSUE TITLE
Bug in Build 29 on a Spigot 1.13 server

### ISSUE THREAD

**Issue by Rocologo** [dmulloy2/LWC#42]
```
[22:04:49] [Server thread/ERROR]: Fatal error trying to convert LWC v4.7.0-SNAPSHOT
org.bukkit.plugin.AuthorNagException: No legacy enum constant for RAIL. Did you forget to define api-version: 1.13 in your plugin.yml?
	at org.bukkit.craftbukkit.v1_13_R1.util.Commodore$1$1.visitFieldInsn(Commodore.java:154) ~[spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
	at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2207) ~[spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1274) ~[spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:679) ~[spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:391) ~[spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
	at org.bukkit.craftbukkit.v1_13_R1.util.Commodore.convert(Commodore.java:130) ~[spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
	at org.bukkit.craftbukkit.v1_13_R1.util.CraftMagicNumbers.processClass(CraftMagicNumbers.java:215) [spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:127) [spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:193) [spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) [spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) [spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_161]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_161]
	at com.griefcraft.util.ProtectionFinder.getProtectionMatchers(ProtectionFinder.java:176) [LWC-4.7.0-B29.jar:?]
	at com.griefcraft.util.ProtectionFinder.matchBlocks(ProtectionFinder.java:122) [LWC-4.7.0-B29.jar:?]
	at com.griefcraft.lwc.LWC.findProtection(LWC.java:1264) [LWC-4.7.0-B29.jar:?]
	at com.griefcraft.lwc.LWC.findProtection(LWC.java:1240) [LWC-4.7.0-B29.jar:?]
	at com.griefcraft.lwc.LWC.findProtection(LWC.java:1230) [LWC-4.7.0-B29.jar:?]
	at com.griefcraft.listeners.LWCEntityListener.entityInteract(LWCEntityListener.java:80) [LWC-4.7.0-B29.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) [spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
	at net.minecraft.server.v1_13_R1.BlockRedstoneOre.stepOn(BlockRedstoneOre.java:40) [spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
	at net.minecraft.server.v1_13_R1.Entity.move(Entity.java:844) [spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
	at net.minecraft.server.v1_13_R1.EntityLiving.a(EntityLiving.java:1912) [spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
	at net.minecraft.server.v1_13_R1.EntityLiving.k(EntityLiving.java:2247) [spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
	at net.minecraft.server.v1_13_R1.EntityInsentient.k(EntityInsentient.java:504) [spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
	at net.minecraft.server.v1_13_R1.EntityMonster.k(SourceFile:35) [spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
	at net.minecraft.server.v1_13_R1.EntitySkeletonAbstract.k(EntitySkeletonAbstract.java:93) [spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
	at net.minecraft.server.v1_13_R1.EntityLiving.tick(EntityLiving.java:2062) [spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
	at net.minecraft.server.v1_13_R1.EntityInsentient.tick(EntityInsentient.java:247) [spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
	at net.minecraft.server.v1_13_R1.EntityMonster.tick(SourceFile:40) [spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
	at net.minecraft.server.v1_13_R1.World.entityJoinedWorld(World.java:1360) [spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
	at net.minecraft.server.v1_13_R1.World.g(World.java:1327) [spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
	at net.minecraft.server.v1_13_R1.World.tickEntities(World.java:1161) [spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
	at net.minecraft.server.v1_13_R1.WorldServer.tickEntities(WorldServer.java:601) [spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
	at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:956) [spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
	at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
```

**Comment by trainphreak** [comment]
Sounds like *shock* 1.13 doesn't handle older data very well. It's almost like md5 was right and you shouldn't try running a 1.13 server with plugins that don't explicitly support 1.13....

Recommend closing this since #39 was opened already to update for 1.13.

**Comment by dmulloy2** [comment]
Should be fixed in https://github.com/dmulloy2/LWC/commit/a028acc773a6660674670ad8d32227f284fc82cd
