### ISSUE TITLE
NullPointerException from optional.blacklistedBlocks

### ISSUE THREAD

**Issue by mibby** [dmulloy2/LWC#44]
LWC dev 30
Paper-1.13 dev 152 (Spigot 1.13)

Testing plugins out in a new 1.13 environment to see what doesn't work. Noticed this error from LWC at start-up.
```
[13:07:41] [Server thread/INFO]: [LWC] Enabling LWC v4.7.0-SNAPSHOT
[13:07:41] [Server thread/INFO]: [LWC] Connecting to SQLite
[13:07:41] [Server thread/INFO]: [LWC] Failed to parse "154" from optional.blacklistedBlocks:
[13:07:41] [Server thread/WARN]: java.lang.NullPointerException
[13:07:41] [Server thread/WARN]: 	at org.bukkit.material.MaterialData.hashCode(MaterialData.java:93)
[13:07:41] [Server thread/WARN]: 	at java.util.HashMap.hash(HashMap.java:339)
[13:07:41] [Server thread/WARN]: 	at java.util.HashMap.put(HashMap.java:612)
[13:07:41] [Server thread/WARN]: 	at java.util.HashSet.add(HashSet.java:220)
[13:07:41] [Server thread/WARN]: 	at com.griefcraft.listeners.LWCBlockListener.loadAndProcessConfig(LWCBlockListener.java:545)
[13:07:41] [Server thread/WARN]: 	at com.griefcraft.listeners.LWCBlockListener.<init>(LWCBlockListener.java:78)
[13:07:41] [Server thread/WARN]: 	at com.griefcraft.lwc.LWCPlugin.registerEvents(LWCPlugin.java:309)
[13:07:41] [Server thread/WARN]: 	at com.griefcraft.lwc.LWCPlugin.onEnable(LWCPlugin.java:206)
[13:07:41] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[13:07:41] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325)
[13:07:41] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[13:07:41] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:433)
[13:07:41] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:347)
[13:07:41] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:231)
[13:07:41] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:764)
[13:07:41] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[13:07:41] [Server thread/INFO]: [LWC] Failed to parse "166" from optional.blacklistedBlocks:
[13:07:41] [Server thread/WARN]: java.lang.NullPointerException
[13:07:41] [Server thread/WARN]: 	at org.bukkit.material.MaterialData.hashCode(MaterialData.java:93)
[13:07:41] [Server thread/WARN]: 	at java.util.HashMap.hash(HashMap.java:339)
[13:07:41] [Server thread/WARN]: 	at java.util.HashMap.put(HashMap.java:612)
[13:07:41] [Server thread/WARN]: 	at java.util.HashSet.add(HashSet.java:220)
[13:07:41] [Server thread/WARN]: 	at com.griefcraft.listeners.LWCBlockListener.loadAndProcessConfig(LWCBlockListener.java:545)
[13:07:41] [Server thread/WARN]: 	at com.griefcraft.listeners.LWCBlockListener.<init>(LWCBlockListener.java:78)
[13:07:41] [Server thread/WARN]: 	at com.griefcraft.lwc.LWCPlugin.registerEvents(LWCPlugin.java:309)
[13:07:41] [Server thread/WARN]: 	at com.griefcraft.lwc.LWCPlugin.onEnable(LWCPlugin.java:206)
[13:07:41] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[13:07:41] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325)
[13:07:41] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[13:07:41] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:433)
[13:07:41] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:347)
[13:07:41] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:231)
[13:07:41] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:764)
[13:07:41] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by dmulloy2** [comment]
Looks like IDs in the config need to be updated. Not sure how much can be done about that plugin-side though.

**Comment by mibby** [comment]
Update the defaults generated by the plugin if it is exclusive for 1.13 forward? This is with a newly generated config. :)
